spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: Product Service
    description: Service that retrive in stock products
    version: 1.0.0
