spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka
    registerWithEureka: false
    fetchRegistry: true
  instance:
    preferIpAddress: true

server:
  port: 8080