server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/johnsales/microservices-springboot
          search-paths: config
          clone-on-start: true
          default-label: main
  application:
    name: config-server

